name: Python CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  install_dependancies_and_run_test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install from requirements.txt if it exists
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          # Always install pytest
          pip install pytest

      # Run tests
      - name: Run tests with pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Add other environment variables if needed
        run: |
          PYTHONPATH=. pytest -v
          # For coverage reporting you could add:
          # pytest --cov=your_package tests/
