name: Python CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      ### Stage 1: Checkout Repo
      - name: Checkout code
        uses: actions/checkout@v4

      ### Stage 2: Install Python & Dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest build
        # Optionally cache dependencies here

      ### Stage 3: Build (e.g., validate/compile package)
      - name: Build distribution packages
        run: |
          python -m build

      ### Stage 4: Test
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PYTHONPATH=. pytest

      ### Stage 5: Package (Artifact)
      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: dist/

  # Optional: PyPI publish (only on release)
  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-packages
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
