name: Python CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      ### Stage 1: Checkout Repo
      - name: Checkout code
        uses: actions/checkout@v4

      ### Stage 2: Install Python & Dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest build
        # Optionally cache dependencies here

      ### Stage 4: Test
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PYTHONPATH=. pytest

